/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_v1_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pipeline Runs */
        get: operations["list_pipeline_runs_api_v1_admin_pipeline_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Review Queue
         * @description Retrieve filtered review cases awaiting administrator action.
         */
        get: operations["list_review_queue_api_v1_admin_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/{case_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Case
         * @description Resolve an open review case with a valid action and transition signal state.
         */
        post: operations["resolve_case_api_v1_admin_reviews__case_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Radar */
        get: operations["get_radar_api_v1_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signals */
        get: operations["list_signals_api_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignDiseaseRequest */
        AssignDiseaseRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "assign_disease";
            /**
             * Disease Id
             * Format: uuid
             */
            disease_id: string;
            /** Note */
            note?: string | null;
        };
        /**
         * BriefPoint
         * @description One bullet of a brief.
         *
         *     `reported` is false when the article never addressed this slot. The text
         *     still has to say something — it says what is missing — because an empty
         *     bullet and an unreported fact would look identical to a reader.
         */
        BriefPoint: {
            /** Reported */
            reported: boolean;
            slot: components["schemas"]["BriefSlot"];
            /** Text */
            text: string;
        };
        /**
         * BriefSlot
         * @description One of the five questions a brief answers, in the order it is asked.
         * @enum {string}
         */
        BriefSlot: "what_where" | "counts" | "timing" | "spread" | "reporting";
        /** Components */
        Components: {
            /**
             * Database
             * @enum {string}
             */
            database: "up" | "down" | "unknown";
            /**
             * Postgis
             * @enum {string}
             */
            postgis: "up" | "down" | "unknown";
        };
        /** CreateEventRequest */
        CreateEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "create_event";
            /** Note */
            note?: string | null;
            /** @default unverified */
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * CredibilityTier
         * @enum {string}
         */
        CredibilityTier: "official" | "high" | "medium" | "unknown";
        /** DismissRequest */
        DismissRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "dismiss";
            /** Note */
            note: string;
        };
        /**
         * EventContextStatus
         * @enum {string}
         */
        EventContextStatus: "none" | "attached" | "ambiguous";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkEventRequest */
        LinkEventRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "link_event";
            /** Event Id */
            event_id?: string | null;
            /** Note */
            note?: string | null;
            /** Target Event Id */
            target_event_id?: string | null;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "alive";
        };
        /**
         * LocationRole
         * @enum {string}
         */
        LocationRole: "primary" | "exposure" | "diagnosis" | "travel" | "reporting" | "affected_area";
        /** NotReadyResponse */
        NotReadyResponse: {
            components: components["schemas"]["Components"];
            /**
             * Error Code
             * @constant
             */
            error_code: "DATABASE_NOT_READY";
            /**
             * Status
             * @constant
             */
            status: "not_ready";
        };
        /**
         * PipelineChain
         * @enum {string}
         */
        PipelineChain: "daily";
        /** PipelineFailureResponse */
        PipelineFailureResponse: {
            /** Error */
            error: string | null;
            stage: components["schemas"]["StageName"];
        };
        /** PipelineRunListResponse */
        PipelineRunListResponse: {
            /** Items */
            items: components["schemas"]["PipelineRunResponse"][];
            /** Limit */
            limit: number;
        };
        /** PipelineRunResponse */
        PipelineRunResponse: {
            /** Backlog */
            backlog: {
                [key: string]: number;
            };
            chain: components["schemas"]["PipelineChain"];
            /** Failures */
            failures: components["schemas"]["PipelineFailureResponse"][];
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Stale */
            is_stale: boolean;
            /** Stage Counts */
            stage_counts: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["PipelineRunStatus"];
            trigger: components["schemas"]["PipelineTrigger"];
            /** Window End */
            window_end: string | null;
            /** Window Start */
            window_start: string | null;
        };
        /**
         * PipelineRunStatus
         * @enum {string}
         */
        PipelineRunStatus: "running" | "succeeded" | "failed";
        /**
         * PipelineTrigger
         * @enum {string}
         */
        PipelineTrigger: "scheduled" | "manual";
        /**
         * Precision
         * @description How specific a resolved location actually is.
         *
         *     Ordered from most to least specific. `unresolved` is a real answer, not a
         *     missing one: the article named a place the gazetteer could not match, which
         *     is different from the article naming no place at all.
         * @enum {string}
         */
        Precision: "place" | "admin2" | "admin1" | "country" | "unresolved";
        /**
         * ProcessingStatus
         * @enum {string}
         */
        ProcessingStatus: "fetched" | "normalized" | "classified" | "extracted" | "geocoded" | "matched" | "published" | "duplicate" | "failed" | "needs_review" | "dismissed";
        /** RadarEventContextResponse */
        RadarEventContextResponse: {
            /** Early Signal Score */
            early_signal_score: number | null;
            /** Evidence Score */
            evidence_score: number | null;
            /** Public Id */
            public_id: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** RadarItemResponse */
        RadarItemResponse: {
            /** Brief */
            brief: components["schemas"]["BriefPoint"][];
            event: components["schemas"]["RadarEventContextResponse"] | null;
            event_context_status: components["schemas"]["EventContextStatus"];
            /** Extraction Confidence */
            extraction_confidence: number;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            location: components["schemas"]["RadarLocationResponse"] | null;
            processing_status: components["schemas"]["ProcessingStatus"];
            /** Published At */
            published_at: string | null;
            signal_type: components["schemas"]["SignalType"];
            source: components["schemas"]["RadarSourceResponse"];
            /** Title English */
            title_english: string;
        };
        /** RadarLocationResponse */
        RadarLocationResponse: {
            /** Country Code */
            country_code: string | null;
            /** Label */
            label: string;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            precision: components["schemas"]["Precision"];
            role: components["schemas"]["LocationRole"];
        };
        /** RadarResponse */
        RadarResponse: {
            /** Hours */
            hours: number;
            /** Items */
            items: components["schemas"]["RadarItemResponse"][];
            /** Limit */
            limit: number;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** RadarSourceResponse */
        RadarSourceResponse: {
            credibility_tier: components["schemas"]["CredibilityTier"];
            /** Is Official */
            is_official: boolean;
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            components: components["schemas"]["Components"];
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** RetryExtractionRequest */
        RetryExtractionRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "retry_extraction";
            /** Note */
            note?: string | null;
        };
        /** RetryGeocodingRequest */
        RetryGeocodingRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "retry_geocoding";
            /** Note */
            note?: string | null;
        };
        /** RetryRetrievalRequest */
        RetryRetrievalRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "retry_retrieval";
            /** Note */
            note?: string | null;
        };
        /** ReviewCandidateEvent */
        ReviewCandidateEvent: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Match Score */
            match_score: number;
            /** Public Id */
            public_id: string;
            /** Title */
            title: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** ReviewCaseResult */
        ReviewCaseResult: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            processing_status: components["schemas"]["ProcessingStatus"];
            resolution: components["schemas"]["ReviewResolution"];
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
            /** Selected Disease Id */
            selected_disease_id?: string | null;
            /** Selected Event Id */
            selected_event_id?: string | null;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
        };
        /** ReviewDiseaseOption */
        ReviewDiseaseOption: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ReviewQueueItem */
        ReviewQueueItem: {
            /** Allowed Resolutions */
            allowed_resolutions?: components["schemas"]["ReviewResolution"][];
            /** Candidate Events */
            candidate_events?: components["schemas"]["ReviewCandidateEvent"][];
            /** Canonical Disease */
            canonical_disease?: string | null;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Extracted Disease Text */
            extracted_disease_text?: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Locations */
            locations?: components["schemas"]["ReviewSignalLocation"][];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            reason: components["schemas"]["ReviewReason"];
            /** Retrieval Attempts */
            retrieval_attempts: number;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
        };
        /** ReviewQueuePage */
        ReviewQueuePage: {
            /** Disease Options */
            disease_options: components["schemas"]["ReviewDiseaseOption"][];
            /** Items */
            items: components["schemas"]["ReviewQueueItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total Open Cases */
            total_open_cases: number;
        };
        /**
         * ReviewReason
         * @enum {string}
         */
        ReviewReason: "retrieval_failed" | "extraction_rejected" | "disease_unresolved" | "location_unresolved" | "event_match_ambiguous" | "content_integrity" | "legacy_unclassified";
        /**
         * ReviewResolution
         * @enum {string}
         */
        ReviewResolution: "retry_retrieval" | "retry_extraction" | "assign_disease" | "retry_geocoding" | "link_event" | "create_event" | "dismiss" | "recovered_automatically";
        /** ReviewSignalLocation */
        ReviewSignalLocation: {
            /** Admin1 Name */
            admin1_name?: string | null;
            /** Country Name */
            country_name?: string | null;
            location_role: components["schemas"]["LocationRole"];
            /** Place Name */
            place_name?: string | null;
            precision: components["schemas"]["Precision"];
            /** Resolved Name */
            resolved_name?: string | null;
        };
        /** SignalEvidenceResponse */
        SignalEvidenceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Published At */
            published_at: string | null;
            /** Raw Text */
            raw_text: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Name */
            source_name: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** SignalListResponse */
        SignalListResponse: {
            /** Items */
            items: components["schemas"]["SignalEvidenceResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Source Count */
            source_count: number;
            /** Total */
            total: number;
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "outbreak_report" | "surveillance_update" | "case_report" | "imported_case" | "public_health_action" | "vaccination_campaign" | "risk_assessment" | "situation_report" | "research" | "rumor" | "unknown";
        /**
         * StageName
         * @description One step of the pipeline. Never a rung of the model ladder: that is a tier.
         * @enum {string}
         */
        StageName: "ingest_who" | "ingest_ecdc" | "discover" | "dedupe" | "extract" | "geocode" | "match";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "officially_confirmed" | "high_credibility" | "signal" | "unverified" | "rumor_monitoring";
        /** VersionResponse */
        VersionResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    version_api_v1_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    list_pipeline_runs_api_v1_admin_pipeline_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_queue_api_v1_admin_reviews_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                reason?: string | null;
                status?: string | null;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_case_api_v1_admin_reviews__case_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRetrievalRequest"] | components["schemas"]["RetryExtractionRequest"] | components["schemas"]["AssignDiseaseRequest"] | components["schemas"]["RetryGeocodingRequest"] | components["schemas"]["LinkEventRequest"] | components["schemas"]["CreateEventRequest"] | components["schemas"]["DismissRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCaseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_radar_api_v1_radar_get: {
        parameters: {
            query?: {
                hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_signals_api_v1_signals_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReadyResponse"];
                };
            };
        };
    };
}
